spring:
    datasource:
        jndi-name: jdbc/epa_db
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect

logging:
    level:
        com.culqi: INFO
    file: ${catalina.home}/logs/epa.log